### ISSUE TITLE
Datastore as a service and thoughts on deployment

### ISSUE THREAD

**Issue by kevinkreiser** [opentraffic/datastore#38]
With the work in #34 we have a process that takes input files form the reporter and produces a tile in the given format. This is basically a run once command. This isnt exactly perfect for use in docker but we have a plan around that.

The current plan is we'll setup a lambda that monitors sqs. The lambda will run as a cron and wake up every 5 minutes. If there is nothing in sqs, it will enumerate everything in s3 (that the reporters reported), and turn those into jobs. Each job will be concerned with 1 or more reporter output files but those files will only touch a single output file (single geographic region and time). It will move those files into a working location under s3, push those jobs into the queue and exit.

Mean while we'll have the datastore farm of ecs containers running a hybrid python java service. The python will be listening to sqs for jobs. It'll pull the jobs off the queue continuously. For each job it will unpack the job message, pull down the relevant tiles from s3, merge them into one by invoking the java program, and then upload the result back to s3 and delete the job from the queue.

Meanwhile the lambda cron from above wakes up and sees that there is still jobs in the queue. At this point it just exists. If the queue was finished burning down it will know that all the stuff in the working s3 location is done, so it will delete that. It can then move the latest files to the working location and enqueue them as new jobs.

We'll also be able to set up auto scale for the datastore workers so that if the queue gets a large influx of data we can spin up more workers to handle the jobs.

**Comment by heffergm** [comment]
Kevin and I discussed a bit more today. After looking into AWS Batch, we're going to proceed with some minor modifications to support that workflow.

Batch appears like it will allow us to run an essentially server-less Datastore system from a management standpoint, as well as make use of spot instances. The workflow will remain basically the same as already laid out by Kevin above, but rather than SQS, we'll use Batch queues. Each job submitted to the queue is really just a command passed to a docker container. Lambda will remain as the mechanism responsible for pushing jobs into the queue. Every job will be passed information related to the work it needs to do (S3 input/output paths).

**Comment by drewda** [comment]
It's running now.
